### ISSUE TITLE
train_tiny问题

### ISSUE THREAD

**Issue by wl4135** [panguxiaoshen/tiny_yolov3#9]
训练的时候，出现这个问题
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train_tiny.py", line 194, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train_tiny.py", line 42, in __init__
    self.trainset            = Dataset('train')
  File "/content/drive/yolov3-tiny/tiny_yolov3-master/tensorflow/src/core/dataset_tiny.py", line 33, in __init__
    self.strides = np.array(cfg.YOLO.TINY_STRIDES)
AttributeError: 'EasyDict' object has no attribute 'TINY_STRIDES'

这个是什么原因？大佬指点一下

**Comment by panguxiaoshen** [comment]
在config.py里，__C.YOLO.TINY_STRIDES           = [16, 32]这一行你是不是注释掉了？

**Comment by wl4135** [comment]
> 在config.py里，__C.YOLO.TINY_STRIDES = [16, 32]这一行你是不是注释掉了？

非常您的帮助，问题解决了，我在改的时候不知道怎么就给注释了。现在开始训练了。再咨询您个问题，tflite文件您尝试过在安卓部署吗？

**Comment by wl4135** [comment]
> 在config.py里，__C.YOLO.TINY_STRIDES = [16, 32]这一行你是不是注释掉了？

您好，我现在训练发现没有使用gpu,我在google colab训练的，发现未使用gpu,请问是不是在训练文件中os.environ["CUDA_VISIBLE_DEVICES"] = '1'改为0？

**Comment by panguxiaoshen** [comment]
看你使用几块GPU了，第一块是‘0’

> > 在config.py里，__C.YOLO.TINY_STRIDES = [16, 32]这一行你是不是注释掉了？
> 
> 非常您的帮助，问题解决了，我在改的时候不知道怎么就给注释了。现在开始训练了。再咨询您个问题，tflite文件您尝试过在安卓部署吗？

安卓部署，2种方式，一种是配置java环境，java调用编译好的tflite库，这种我没用过。另一种方式，编译tflite的so库， 通过jni用c++加载tflite。java我不熟，编译过程也有很多坑，这部分无法帮你了

**Comment by wl4135** [comment]
> 看你使用几块GPU了，第一块是‘0’
> 
> > > 在config.py里，__C.YOLO.TINY_STRIDES = [16, 32]这一行你是不是注释掉了？
> > 
> > 
> > 非常您的帮助，问题解决了，我在改的时候不知道怎么就给注释了。现在开始训练了。再咨询您个问题，tflite文件您尝试过在安卓部署吗？
> 
> 安卓部署，2种方式，一种是配置java环境，java调用编译好的tflite库，这种我没用过。另一种方式，编译tflite的so库， 通过jni用c++加载tflite。java我不熟，编译过程也有很多坑，这部分无法帮你了

非常感谢您的指点，我只有一块gpu,估计改为0就可以了，一会训练完了我试试。安卓我研究一下。非常感谢，优秀！
